"""统一错误响应的单元测试（API_CONTRACT §0.1）。

重点验证：错误体结构统一、敏感信息不回显、未预期异常不透出内部信息。
"""

from __future__ import annotations

import pytest

from app.core.errors import (
    AgentTimeoutError,
    AgentTraceError,
    AgentValidationError,
    EvaluationNotFoundError,
    InvalidArgumentError,
    RunNotFoundError,
    RunNotReplayableError,
    TracePersistenceError,
    generate_request_id,
)

pytestmark = pytest.mark.unit


class TestErrorCodeMapping:
    """每个异常的 error_code 与 http_status 必须与契约表格一致。"""

    @pytest.mark.parametrize(
        ("exc_class", "expected_code", "expected_status"),
        [
            (InvalidArgumentError, "INVALID_ARGUMENT", 400),
            (AgentValidationError, "AGENT_VALIDATION_ERROR", 422),
            (RunNotFoundError, "RUN_NOT_FOUND", 404),
            (EvaluationNotFoundError, "EVALUATION_NOT_FOUND", 404),
            (RunNotReplayableError, "RUN_NOT_REPLAYABLE", 409),
            (TracePersistenceError, "TRACE_WRITE_FAILED", 500),
            (AgentTimeoutError, "AGENT_TIMEOUT", 504),
        ],
    )
    def test_mapping(self, exc_class, expected_code: str, expected_status: int) -> None:
        exc = exc_class("测试消息")
        assert exc.error_code == expected_code
        assert exc.http_status == expected_status

    def test_all_errors_subclass_base(self) -> None:
        for exc_class in (
            InvalidArgumentError,
            AgentValidationError,
            RunNotFoundError,
            EvaluationNotFoundError,
            RunNotReplayableError,
            TracePersistenceError,
            AgentTimeoutError,
        ):
            assert issubclass(exc_class, AgentTraceError)

    def test_agent_validation_error_is_not_400(self) -> None:
        """语义非法必须是 422 而非 400，否则调用方无法区分。

        契约 API_CONTRACT §2：question 全空白 → 422 AGENT_VALIDATION_ERROR；
        字段超长/格式错 → 400 INVALID_ARGUMENT。两者的处理策略不同。
        """
        assert AgentValidationError("x").http_status == 422
        assert InvalidArgumentError("x").http_status == 400


class TestErrorPayloadStructure:
    """响应体结构必须是 {"error": {code, message, details, request_id}}。"""

    def test_payload_shape(self) -> None:
        exc = RunNotFoundError("Run 不存在。", details={"run_id": "run_abc"})
        payload = exc.to_payload("req_123")

        assert set(payload) == {"error"}
        assert set(payload["error"]) == {"code", "message", "details", "request_id"}
        assert payload["error"]["code"] == "RUN_NOT_FOUND"
        assert payload["error"]["request_id"] == "req_123"
        assert payload["error"]["details"] == {"run_id": "run_abc"}

    def test_request_id_autogenerated_when_absent(self) -> None:
        payload = RunNotFoundError("x").to_payload()
        assert payload["error"]["request_id"].startswith("req_")
        assert len(payload["error"]["request_id"]) > 8

    def test_details_defaults_to_empty_dict(self) -> None:
        payload = RunNotFoundError("x").to_payload("req_1")
        assert payload["error"]["details"] == {}


class TestErrorMessageSanitization:
    """错误消息与 details 必须脱敏且截断，避免回显敏感数据。"""

    def test_message_redacts_api_key_pattern(self) -> None:
        exc = InvalidArgumentError("调用失败，key=sk-abcdefghijklmnopqrstuvwxyz123456 无效")
        assert "sk-abcdefghijklmnopqrstuvwxyz123456" not in exc.message
        assert "[REDACTED" in exc.message

    def test_message_is_truncated(self) -> None:
        """超长消息必须截断，避免把整个请求体回显给调用方。"""
        exc = InvalidArgumentError("x" * 5000)
        assert len(exc.message) <= 500

    def test_details_values_redacted_and_truncated(self) -> None:
        exc = InvalidArgumentError(
            "参数错误",
            details={
                "token": "abcdef123456",
                "long_value": "y" * 2000,
                "count": 7,
                "flag": False,
            },
        )
        assert "abcdef123456" not in str(exc.details)
        assert len(exc.details["long_value"]) <= 300
        # 非字符串类型保持原样，便于调用方程序化处理
        assert exc.details["count"] == 7
        assert exc.details["flag"] is False

    def test_details_list_truncated_to_twenty(self) -> None:
        exc = InvalidArgumentError("x", details={"items": [f"item-{i}" for i in range(100)]})
        assert len(exc.details["items"]) == 20

    def test_details_key_redacted(self) -> None:
        """键名本身也可能含敏感词。"""
        exc = InvalidArgumentError("x", details={"api_key": "abcdef123456"})
        dumped = str(exc.details)
        assert "abcdef123456" not in dumped


class TestRequestIdGeneration:
    """请求 ID 格式，用于把调用方看到的错误与日志关联。"""

    def test_prefix_and_uniqueness(self) -> None:
        ids = {generate_request_id() for _ in range(100)}
        assert len(ids) == 100
        assert all(rid.startswith("req_") for rid in ids)
